### ISSUE TITLE
Dictionary attack?

### ISSUE THREAD

**Issue by d33tah** [glv2/bruteforce-luks#1]
I hadn't seen that in README - is there a way to trigger dictionary brute-force attack?

**Comment by glv2** [comment]
No, for the moment this program doesn't use dictionary files.

**Comment by srulikuk** [comment]
Hi, I am trying to install but get error "configure:  error: cryptsetup library required" but i have it! how can i resolve this?

**Comment by d33tah** [comment]
@srulikuk: This sounds like a separate issue. I suggest you ask your Linux distribution's support community how you can install cryptsetup library in your system.

**Comment by srulikuk** [comment]
Is it dependent on a particular version of cryptsetup library? I am using Ubuntu 14.04

**Comment by glv2** [comment]
Did you install the libcryptsetup-dev package ?

**Comment by glv2** [comment]
I added a dictionary mode to the program (commit 20060791caea16ac24f232a367983982d2bc8292). You can use it with the -f command line option.

**Comment by d33tah** [comment]
W dniu 31.10.2015 o 16:25, glv2 pisze:
> I added a dictionary mode to the program (commit 20060791caea16ac24f232a367983982d2bc8292). You can use it with the -f command line option.

Nice! :) I already hacked up my own tiny Python program to do what I
needed to, but I believe that the dictionary mode can be useful for
others. Thank you :)

**Comment by srulikuk** [comment]
i installed libcryptsetup-dev and got it working, i have a few other issues, with start another thread.
