### ISSUE TITLE
Include installation requirements in Readme

### ISSUE THREAD

**Issue by LRonHubs** [glv2/bruteforce-luks#10]
```
sudo apt-get install dh-autoreconf
sudo apt-get install libcryptsetup-dev
```

These are the  only two commands you need to run when booting from a live USB (Ubuntu 16.04). I figure since I always have to run a couple Googles to find this it should be put in the Readme.

**Comment by glv2** [comment]
Done in commit 865c9b676e7456533aadbf9eae324a5406f6f2a7.
