### ISSUE TITLE
option to stop and restart

### ISSUE THREAD

**Issue by lr1980** [glv2/bruteforce-luks#11]
it would be nice to stop and restart the program with saved position :)

**Comment by illwieckz** [comment]
it's a good idea, I think the best implementation would be to do it like ddrescue does: using an optional journal file to resume any aborted run, so you don't care to stop it, only to resume it if something goes wrong (like unexpected power loss or system crash).

**Comment by ciroiriarte** [comment]
Can we please get the "resume" option?

**Comment by glv2** [comment]
I don't have the time to work on it right now, but if someone make a pull request with this feature I'll gladly merge it.

**Comment by glv2** [comment]
I added a *"-w file"* option to save/restore the program state from a file in the *master* branch (commit f060da2359cad6f1943b01aa3695f2c69fc9b6d8).
