### ISSUE TITLE
[Feature request] Display progress during operation without USR1

### ISSUE THREAD

**Issue by jbruchon** [glv2/bruteforce-luks#16]
It would be nice to have a command option to show the progress while brute forcing. I'm thinking of something like this, refreshed once per second:

`Tried 123 of 33333, last: 'password1234'`

**Comment by eliadb** [comment]
Did you read the documentation?

> Print progress info:
>
> `pkill -USR1 -f bruteforce-luks`

**Comment by jbruchon** [comment]
> Did you read the documentation?

Yes, and you'll note that my request is for a different feature from what you've suggested. I am not asking for the ability to show progress by sending an external signal to the program. I want the program to show its progress regularly without needing to create and manage an extra process that kicks it every X intervals.

**Comment by glv2** [comment]
I added a "*-v n*" option to print progress info every *n* seconds in the *master* branch (commit 6ee8f36f4997d05aa64239afd5961fb3a677a224).

**Comment by jbruchon** [comment]
Thank you!
