### ISSUE TITLE
Error after less than 10 tries

### ISSUE THREAD

**Issue by xvovx** [glv2/bruteforce-luks#17]
Pulled a drive that I had set aside sometime in 2014 after seemingly have forgotten the luks password. Started dabbling with this script using all numbers as well as all possible special characters on a US keyboard and felt like the script was hanging as it created a new line with just ">".

So I decided to do something short which I knew would not work and then received these errors.

root@kali:~# bruteforce-luks -t 8 -l 5 -m 26 -s "23456789" /dev/sda1Error: access to the LUKS volume denied.

Error: access to the LUKS volume denied.

Error: access to the LUKS volume denied.

Tried / Total passwords: 8 / 3.45407e+23
Tried passwords per second: 1.333333
Last tried password: 72222
Total space searched: 0.000000%
ETA: tal 19 qun 2038  3:14:07 saaku UTC

Password not found
root@kali:~# bruteforce-luks -t 8 -s "23456789" /dev/sda1
Error: access to the LUKS volume denied.

Error: access to the LUKS volume denied.

Error: access to the LUKS volume denied.

Error: access to the LUKS volume denied.

Tried / Total passwords: 8 / 1.9174e+07
Tried passwords per second: 1.142857
Last tried password: 8
Total space searched: 0.000042%
ETA: gum 26 qun 2018 12:45:53 carra UTC

Password not found
root@kali:~# bruteforce-luks -t 8 -s "23456789" /dev/sda1
Error: access to the LUKS volume denied.

Error: access to the LUKS volume denied.

*** Error in `bruteforce-luks': double free or corruption (!prev): 0xb33240c8 ***
Aborted
root@kali:~# bruteforce-luks -t 6 -s "23456789" /dev/sda1
Error: access to the LUKS volume denied.

Tried / Total passwords: 6 / 1.9174e+07
Tried passwords per second: 2.000000
Last tried password: 7
Total space searched: 0.000031%
ETA: sab 04 xim 2017  7:29:37 saaku UTC

Password not found

**Comment by xvovx** [comment]
I also tried the method of copying the Luks header with dd and had the same results

**Comment by glv2** [comment]
Could you try with the last version (1.3.0) to see if it gives a more detailed error message?

**Comment by xvovx** [comment]
Tried with 2,4, and 6 threads out of 8 with the same result.

root@kali:/# bruteforce-luks -t 6 -l 6 -m 12 -s "1234567890" /sbin/bruteforce-luks/MyFiles/luks-header
Tried / Total passwords: 6 / 1.11111e+12
Tried passwords per second: 2.000000
Last tried password: 111116
Total space searched: 0.000000%
ETA: tal 19 qun 2038  3:14:07 saaku UTC

Password not found

**Comment by xvovx** [comment]
Here is the header I am working with as well
[luks-header.tar.gz](https://github.com/glv2/bruteforce-luks/files/1156850/luks-header.tar.gz)

**Comment by glv2** [comment]
I tried on my system with your LUKS header, and the program doesn't stop after a few attempts.

What is the version of the *cryptsetup* library on your machine?

**Comment by xvovx** [comment]
1.7.3

**Comment by xvovx** [comment]
Well, I reinstalled a few things which I probably did not need to do, and then started removing options one by one until finally I removed the threads option completely...

And it seems to work now, but kind of defeats the hope of running this faster as there are 8 cores in the Exynos5422 chip in my Odroid xu4 that I was hoping to leave dedicated to this task.

However, another issue I am running into is that including special character sets is returning errors. There is a very good possibility that I will need to run all numbers and special charecters available on a US keyboard. Leaving the entire set in " " I am returned with either a new line " > " or one of a few other errors as it seems bash is trying to take the set as a direct command.

**Comment by glv2** [comment]
To prevent *bash* from interpreting *'$'* or *'!'* characters, you can use simple quotes around the character set, and if you need the simple quote character in the character set you can put it between double quotes next to the other characters:

``` bash
bruteforce-luks -s "'"'0123456789$abcd!efgh*/\...' ...
```
