### ISSUE TITLE
Is it possible to increase the pass/sec rate?

### ISSUE THREAD

**Issue by kasra** [glv2/bruteforce-luks#19]
Thanks for this very useful tool. 

My current best rate is 1.8 pass/sec [8 threads on an i7-6820HQ] - unfortunately this is not fast enough for my dictionary size. Is there a way to increase this? (perhaps via hacking cryptsetup?)

**Comment by glv2** [comment]
I think the only ways to significantly increase the rate are having faster CPUs and having more CPUs.

**Comment by kasra** [comment]
I understand - thanks again.
