### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by stephane-21** [glv2/bruteforce-luks#21]
With the version 1.3.1-1 from Ubuntu 19.04 repositories :

`user@PC:~$ sudo bruteforce-luks -t 8 -l 13 -m13 -b "AZERT$" -e "012345" -s "*ù$0123456789" -v 3 /dev/sda3

Tried / Total passwords: 0 / 15
Tried passwords per second: 0,000000
Last tried password: AZERT$2012345
Total space searched: 0,000000%
Segmentation fault

user@PC:~$ 
`

**Comment by glv2** [comment]
This should be fixed in version 1.3.2.
