### ISSUE TITLE
ERR: Not valid/N Permission to LUKS volume

### ISSUE THREAD

**Issue by jtagcat** [glv2/bruteforce-luks#24]
![image](https://user-images.githubusercontent.com/38327267/69001263-5119fa00-08d3-11ea-907e-d269d9c5c596.png)
![image](https://user-images.githubusercontent.com/38327267/69001265-59723500-08d3-11ea-9d61-f8fcb6317680.png)
Currently using [Regolith](https://regolith-linux.org/) as an OS. Everywhere else the drive shows up.

**Comment by glv2** [comment]
I added a patch to support LUKS2 volumes (commit 2f9325b55cf5500d6fb23cc88000eeb852fb1864).
Could you compile the code in the master branch and test if it solves your problem?

**Comment by jtagcat** [comment]
That solved it, much appreciated!
