### ISSUE TITLE
Install issues - "./configure: no such file or directory"

### ISSUE THREAD

**Issue by jataadroid** [glv2/bruteforce-luks#8]
When attempting to install on Kali by inputting "./configure && make && make install" it outputs "./configure: no such file or directory"

I am in the target directory with root access. Kali installed fresh within the last 24 hours.

**Comment by glv2** [comment]
Run ```./autogen.sh```, it should generate the ```configure``` script.

**Comment by jataadroid** [comment]
Output:
    ./autogen.sh: 6: ./autogen.sh: autoreconf: not found

**Comment by glv2** [comment]
You must install the *autoconf* package (and *automake* too if it is not already installed).

**Comment by jataadroid** [comment]
This has moved in to another category of issues. Root issue no longer relates to LUKS bruteforce.
